/** @type {import('@docusaurus/types').Config} */
module.exports = {
  title: "Prompt Registry",
  tagline: "Hierarchical Agent Prompt Documentation",
  favicon: "img/favicon.ico",

  // Set the production url of your site here
  url: "https://yourusername.github.io",
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: "/prompt-registry/",

  // GitHub pages deployment config
  organizationName: "yourusername",
  projectName: "prompt-registry",

  onBrokenLinks: "throw",
  onBrokenMarkdownLinks: "warn",

  // Enable Mermaid diagrams
  markdown: {
    mermaid: true,
  },

  themes: ["@docusaurus/theme-mermaid"],

  presets: [
    [
      "classic",
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: "./sidebars.js",
          // Use autogenerated sidebar
          sidebarCollapsed: false,
        },
        theme: {
          customCss: "./src/css/custom.css",
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      // Replace with your project's social card
      image: "img/docusaurus-social-card.jpg",
      navbar: {
        title: "Prompt Registry",
        logo: {
          alt: "Prompt Registry Logo",
          src: "img/logo.svg",
        },
        items: [
          {
            type: "docSidebar",
            sidebarId: "docsSidebar",
            position: "left",
            label: "Agents",
          },
          {
            href: "https://github.com/yourusername/prompt-registry",
            label: "GitHub",
            position: "right",
          },
        ],
      },
      footer: {
        style: "dark",
        links: [
          {
            title: "Docs",
            items: [
              {
                label: "Agent Overview",
                to: "/docs/overview/flows",
              },
            ],
          },
          {
            title: "Community",
            items: [
              {
                label: "GitHub",
                href: "https://github.com/yourusername/prompt-registry",
              },
            ],
          },
        ],
        copyright: `Copyright © ${new Date().getFullYear()} Prompt Registry. Built with Docusaurus.`,
      },
      prism: {
        theme: require("prism-react-renderer/themes/github"),
        darkTheme: require("prism-react-renderer/themes/dracula"),
      },
    }),
};
